name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push docker image
        run: | 
          docker build -t cygnetops/react-test -f Dockerfile.dev .
          docker push cygnetops/react-test

        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
          AWS_REGION: "ap-south-1"

        run: |
          eb init -p docker cygnetops/react-test --region ap-south-1
          eb deploy 

      
    
